name: venv_equipamentos
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=he774522_0
  - ca-certificates=2022.10.11=haa95532_0
  - certifi=2022.9.24=py310haa95532_0
  - libffi=3.4.2=hd77b12b_4
  - openssl=1.1.1s=h2bbff1b_0
  - pip=22.2.2=py310haa95532_0
  - python=3.10.6=hbb2ffb3_1
  - setuptools=65.5.0=py310haa95532_0
  - sqlite=3.39.3=h2bbff1b_0
  - tk=8.6.12=h2bbff1b_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wheel=0.37.1=pyhd3eb1b0_0
  - wincertstore=0.2=py310haa95532_2
  - xz=5.2.6=h8cc25b3_0
  - zlib=1.2.13=h8cc25b3_0
  - pip:
    - altair==4.2.0
    - attrs==22.1.0
    - baselineremoval==0.1.1
    - blinker==1.5
    - cachetools==5.2.0
    - charset-normalizer==2.1.1
    - click==8.1.3
    - colorama==0.4.6
    - commonmark==0.9.1
    - decorator==5.1.1
    - entrypoints==0.4
    - gitdb==4.0.9
    - gitpython==3.1.29
    - idna==3.4
    - importlib-metadata==5.0.0
    - jinja2==3.1.2
    - joblib==1.2.0
    - jsonschema==4.17.0
    - markupsafe==2.1.1
    - numpy==1.23.4
    - packaging==21.3
    - pandas==1.5.1
    - pillow==9.3.0
    - plotly==5.11.0
    - protobuf==3.20.3
    - pyarrow==10.0.0
    - pydeck==0.8.0
    - pygments==2.13.0
    - pympler==1.0.1
    - pyparsing==3.0.9
    - pyrsistent==0.19.2
    - python-dateutil==2.8.2
    - pytz==2022.6
    - pytz-deprecation-shim==0.1.0.post0
    - requests==2.28.1
    - rich==12.6.0
    - scikit-learn==1.1.3
    - scipy==1.9.3
    - semver==2.13.0
    - six==1.16.0
    - smmap==5.0.0
    - streamlit==1.14.0
    - tenacity==8.1.0
    - threadpoolctl==3.1.0
    - toml==0.10.2
    - toolz==0.12.0
    - tornado==6.2
    - typing-extensions==4.4.0
    - tzdata==2022.6
    - tzlocal==4.2
    - urllib3==1.26.12
    - validators==0.20.0
    - watchdog==2.1.9
    - zipp==3.10.0
prefix: C:\Users\guilherme220044\Anaconda3\envs\venv_equipamentos
